spring:
  application:
    name: ExposeIT
  datasource:
    url: jdbc:postgresql://localhost:5432/ExposeIT
    username: Sarthak
    password: 12345678
    driver-class-name: org.postgresql.Driver
  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  elasticsearch:
    uris: https://exposeit-c3185a.es.asia-south1.gcp.elastic.cloud:443
    api-key: WlpVRmpKNEJxVU16Tk1QaHFDXzk6cjBaR1hQeW03dnVuYlA2aGJxSDltUQ==

application:
  security:
    jwt: ";w{28etjQiiJ.Q--Gu42fU=;D}xa]>BLYpBP(HnUw/}"
    jwt-expiration: 900000  #15 mins
    refresh-expiration: 1296000000 #15 days