spring:
  application:
    name: ExposeIT
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  elasticsearch:
    uris: ${SPRING_ELASTICSEARCH_URIS:http://elasticsearch:9200}

application:
  security:
    jwt: ";w{28etjQiiJ.Q--Gu42fU=;D}xa]>BLYpBP(HnUw/}"
    jwt-expiration: 900000  #15 mins
    refresh-expiration: 1296000000 #15 days

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always